import { Box, Typography } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box
        sx={{
          height: '100vh',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          // background: 'linear-gradient(45deg, red, blue)',
          background: '#463db9',
        }}
      >
        <Box
          sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            // background: 'white',
            // boxShadow: '0 0 30px rgba(0, 0, 0, 0.3)',
            px: 8,
            py: 4,
          }}
        >
          <Box
            sx={{
              fontWeight: 900,
              fontSize: 50,
              background: 'linear-gradient(45deg, red, blue)',
              backgroundSize: '100vw',
              backgroundClip: 'text',
              // color: 'transparent',
              fontFamily: 'Montserrat',
              // textShadow: '0 0 20px black',
              filter: 'drop-shadow(0 0 0.2vw rgba(0,0,0,0.3))',
              color: '#eda439',
            }}
          >
            <Box
              component='span'
              sx={{ fontSize: '3vw', fontWeight: 700, lineHeight: 1 }}
            >
              Hello,{' '}
            </Box>
            <Box
              component='span'
              sx={{ fontSize: '2vw', fontWeight: 400, lineHeight: 1.3 }}
            >
              my name is
            </Box>
            <Box
              sx={{
                fontSize: '7vw',
                fontWeight: 800,
                lineHeight: 1,
              }}
            >
              Norbert Niziolek
            </Box>
          </Box>
          <Box sx={{ display: 'flex', flexDirection: 'column' }}>
            <h3>about me</h3>
            <h3>projects</h3>
            <h3>extensions</h3>
            <h3>autohotkey</h3>
          </Box>
        </Box>
      </Box>
    </div>
  );
};

export default Home;
